# Generated by Django 5.1.7 on 2025-03-18 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='TeamSubTask_Assign/')),
                ('deadline', models.DateField()),
                ('Assigned_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('submited', 'submited'), ('pending', 'pending'), ('In Progress', 'In Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='TeamSubSubmitted_Task/')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TaskSubSubmmited_by', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='TeamSubTasksubmitted', to='leader.subtaskassigned')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(default=' ', max_length=200)),
                ('Created_on', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('Created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Team_Created_By', to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Team_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtaskassigned',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='which_teams_task', to='leader.team'),
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('joined_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leader.team')),
            ],
        ),
    ]
