# Generated by Django 5.1.7 on 2025-03-18 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.TextField(max_length=300)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='Task_Assign/')),
                ('deadline', models.DateField()),
                ('given_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('submited', 'submited'), ('pending', 'pending'), ('In Progress', 'In Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20)),
                ('Assigened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Task_assignment_by', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Task_assignment_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='Submitted_Task/')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20)),
                ('score', models.CharField(choices=[(2.5, 'Bad'), (5, 'Average'), (7.5, 'Good'), (10, 'Very Good')], max_length=4, null=True)),
                ('Task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task_assigned')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Task_Submmited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='TeamTask_Assign/')),
                ('deadline', models.DateField()),
                ('given_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('submited', 'submited'), ('pending', 'pending'), ('In Progress', 'In Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20)),
                ('Assigened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_TeamTask_assignment_by', to=settings.AUTH_USER_MODEL)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Task_assignment_to_team', to='leader.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTaskSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='TeamSubmitted_Task/')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20)),
                ('score', models.CharField(choices=[(2.5, 'Bad'), (5, 'Average'), (7.5, 'Good'), (10, 'Very Good')], max_length=4, null=True)),
                ('Task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.teamtaskassign')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
