# Generated by Django 5.1.7 on 2025-03-18 03:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftStartTime', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(22, 0), '10:00 PM')])),
                ('shiftEndTime', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(22, 0), '10:00 PM')])),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='department.department')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('startTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('Remark', models.CharField(choices=[('Late', 'Late'), ('Over Time', 'Over Time'), ('On Time', 'On Time')], default='On Time', max_length=20)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Half day', 'Half day')], default='Present', max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('attendance_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.attendancedetails')),
            ],
            options={
                'unique_together': {('emp', 'date')},
            },
        ),
    ]
